helmelar_admin:
    resource: "@HelmelarAdminBundle/Resources/config/routing.yml"
    prefix:   /

helmelar_user:
    resource: "@HelmelarUserBundle/Resources/config/routing.yml"
    prefix:   /

helmelar_game:
    resource: "@HelmelarGameBundle/Resources/config/routing.yml"
    prefix:   /

helmelar_player:
    resource: "@HelmelarPlayerBundle/Resources/config/routing.yml"
    prefix:   /

helmelar_site:
    resource: "@HelmelarSiteBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
