parameters:
#    helmelar_user.example.class: Helmelar\UserBundle\Example

services:
#    helmelar_user.example:
#        class: %helmelar_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
