parameters:
#    helmelar_site.example.class: Helmelar\SiteBundle\Example

services:
#    helmelar_site.example:
#        class: %helmelar_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
